### ISSUE TITLE
Change the default video source

### ISSUE THREAD

**Issue by casmeiron** [AgoraIO-Community/react-native-agora#351]
Hi,

I want to use the follow in react-native:

`            mRtcEngine.setVideoSource(new AgoraTextureCamera(this, 1280, 720));`

Is it possible? In Java I can do that. How can I access such API in react-native?

Thanks!

**Comment by RoJoHub** [comment]
From native(iOS) doc.
```
In real-time communications, the SDK uses the default video input source (the built-in camera) to publish streams. To use an external video source, call AgoraVideoSourceProtocol to set the custom video source and then use this method to add the external video source into the SDK.
```

This is a very customized feature.
You can use an external video source by use this api, such as video from `sysyem photo album`
The `setVideoSource` api is not currently exported in react-native, because it involves native api.

If you have similar needs, I suggest you need iOS and Android development For reacr-native lib

**Comment by VikasSahu** [comment]
Hi @RoJoHub @casmeiron  I want to pass custom video from DeepAR SDK (https://github.com/DeepARSDK/example-reactnative), how can I implement with agora-react-0native?

Please help.
