### ISSUE TITLE
[expo] Cannot read properties of undefined (reading 'prefix')

### ISSUE THREAD

**Issue by kyooryoo** [AgoraIO-Community/react-native-agora#478]
Replicate the issue by adding the following code block to a new expo project at *https://snack.expo.dev/*
```
import RtcEngine, {
  ChannelProfile,
  ClientRole,
  RtcEngineContext,
  RtcLocalView,
  RtcRemoteView,
} from 'react-native-agora';
```
<img width="234" alt="截屏2022-02-18 上午8 43 19" src="https://user-images.githubusercontent.com/16432725/154595868-ae3ae664-67f9-4c67-b73e-24b6c9cb40ce.png">
<img width="434" alt="截屏2022-02-18 上午8 44 28" src="https://user-images.githubusercontent.com/16432725/154595942-a536028e-b3f0-4d50-ba42-cd695e3d9302.png">
Run android emulator returns the same error.

I guess the issue on *react-native-agora* source code.
Please refer to [Resolving The TypeError: Cannot Read Property of Undefined in JavaScript](https://rollbar.com/blog/javascript-typeerror-cannot-read-property-of-undefined/) which I hope could be helpful.

**Comment by LichKing-2234** [comment]
pls refer to https://github.com/AgoraIO-Community/react-native-agora/issues/188

**Comment by EkaanshArora** [comment]
@kyooryoo since `react-native-agora` package uses native code, it cannot be use with expo go or snack. You can either use the bare workflow as suggested or you can use custom development clients with the managed workflow. I have described how to do this using this package and the UIKit [here](https://www.agora.io/en/blog/building-a-video-calling-app-using-the-agora-sdk-on-expo-react-native/).

**Comment by kuriel-trivu** [comment]
Expo now supports native modules with the new EAS Build, when adding this plugin 

![image](https://user-images.githubusercontent.com/46456105/174526696-b901d879-f644-4415-a249-e283661b4e91.png)

The team must see:

https://docs.expo.dev/guides/config-plugins/#creating-a-plugin

To make this repo Expo EAS plugin compatible.
